default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: passwordless-auth-api
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>

test:
  <<: *default
  database: passwordless-auth-api_test
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>

production:
  <<: *default
  database: passwordless-auth-api
  username: habitable_web_api
  password: <%= ENV['HABITABLE_WEB_API_DATABASE_PASSWORD'] %>
